base/urls.py
from django.urls import path
from .views import MedicineList, MedicineDetail, MedicineCreate, MedicineUpdate, MedicineDelete, CustomLoginView, RegisterPage, UserMedicineList, contact_view,UserListView, test_404_view
from django.contrib.auth.views import LogoutView
from django.conf.urls import handler404

# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('', MedicineList.as_view(), name="medicines"),
    path('medicine/<int:pk>/', MedicineDetail.as_view(), name='medicine'),
    path('medicine-create/', MedicineCreate.as_view(), name='medicine-create'),
    path('medicine-update/<int:pk>/', MedicineUpdate.as_view(), name='medicine-update'),
    path('medicine-delete/<int:pk>/', MedicineDelete.as_view(), name='medicine-delete'),
    path('contact/', contact_view, name='contact'),
    path('user/<int:user_id>/medicines/', UserMedicineList.as_view(), name='user-medicines'),  # User medicines path
    path('user-list/', UserListView.as_view(), name='user-list'),
    path('test-404/', test_404_view, name='test-404'),  # Add this line
]

handler404 = 'base.views.custom_404'

first_aid_kit_mgmt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Medicine(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True, blank = True)
    medicine_name = models.CharField(max_length = 200)
    description = models.TextField()
    quantity = models.PositiveIntegerField()
    expiry_date = models.DateField()

    def __str__(self):
        return self.medicine_name

    class Meta:
        ordering = ['expiry_date']

base/forms.py
from django import forms
from .models import Medicine
from django.contrib.auth.models import User

class MedicineForm(forms.ModelForm):
    class Meta:
        model = Medicine
        fields = ['medicine_name', 'description', 'quantity', 'expiry_date', 'user']
        widgets = {
            'user': forms.Select(attrs={'class': 'form-control'}),
            'medicine_name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'expiry_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super(MedicineForm, self).__init__(*args, **kwargs)
        self.fields['user'].queryset = User.objects.all()  # Show all users

base/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth import get_user_model

from django.contrib.auth.models import User


from .models import Medicine
from .forms import MedicineForm

from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages

from django.utils import timezone
from datetime import timedelta

from django.core.paginator import Paginator

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from .mixins import AdminRequiredMixin
# Create your views here.

class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        user = self.request.user
        if user.is_authenticated:
            if user.is_staff:  # Check if the user is an admin
                return reverse_lazy('admin:index')  # Redirect to the admin page
            return reverse_lazy('medicines')  # Redirect to the medicines page
        return super().get_success_url()  # Fallback


class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('medicines')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('medicines')
        return super(RegisterPage, self).get(*args, **kwargs)



class MedicineList(LoginRequiredMixin, ListView):
    model = Medicine
    context_object_name = 'medicines'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Check if the user is an admin
        if self.request.user.is_staff:
            context['medicines'] = Medicine.objects.all()  # Admin sees all medicines
        else:
            context['medicines'] = context['medicines'].filter(user=self.request.user)  # Regular user sees their medicines

        # Search functionality
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['medicines'] = context['medicines'].filter(
                medicine_name__icontains=search_input)

        context['search_input'] = search_input

        # Check for expiring medicines
        one_month_from_now = timezone.now() + timedelta(days=30)
        expiring_medicines = context['medicines'].filter(expiry_date__lt=one_month_from_now)

        context['expiring_medicines'] = expiring_medicines

        # Handle pagination
        per_page = int(self.request.GET.get('per_page', 10))  # Get the number of items per page from the GET parameters, default to 10
        paginator = Paginator(context['medicines'], per_page)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context['page_obj'] = page_obj
        context['per_page'] = per_page

        return context



class MedicineDetail(LoginRequiredMixin, DetailView):
    model = Medicine
    context_object_name = 'medicine'

class MedicineCreate(LoginRequiredMixin, CreateView):
    model = Medicine
    form_class = MedicineForm
    success_url = reverse_lazy('medicines')

    def form_valid(self, form):
        if not self.request.user.is_staff:
            # Set the user to the currently logged-in user if not admin
            form.instance.user = self.request.user
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if not self.request.user.is_staff:
            # Remove the 'user' field for non-admin users
            form.fields.pop('user', None)
        return form


class MedicineUpdate(LoginRequiredMixin, UpdateView):
    model = Medicine
    form_class = MedicineForm
    success_url = reverse_lazy('medicines')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if not self.request.user.is_staff:
            # Remove the 'user' field for non-admin users
            form.fields.pop('user', None)
        return form

class MedicineDelete(LoginRequiredMixin, DeleteView):
    model = Medicine
    context_object_name = 'medicine'
    success_url = reverse_lazy('medicines')

    def get_queryset(self):
        # Allow admins to delete any medicine, otherwise filter by the current user
        if self.request.user.is_staff:
            return self.model.objects.all()
        return self.model.objects.filter(user=self.request.user)

class UserMedicineList(LoginRequiredMixin,AdminRequiredMixin, ListView):
    model = Medicine
    context_object_name = 'medicines'
    template_name = 'base/user_medicines.html'

    def get_queryset(self):
        user_id = self.kwargs['user_id']
        return Medicine.objects.filter(user__id=user_id)  # Fetch medicines for the specified user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs['user_id']
        context['user'] = User.objects.get(id=user_id)  # Add the user to the context

        search_input = self.request.GET.get('search-area') or ''
        medicines = context['medicines']

        if search_input:
            medicines = medicines.filter(medicine_name__icontains=search_input)

        context['medicines'] = medicines
        context['search_input'] = search_input

        # Check for expiring medicines
        one_month_from_now = timezone.now() + timedelta(days=30)
        expiring_medicines = context['medicines'].filter(expiry_date__lt=one_month_from_now)

        context['expiring_medicines'] = expiring_medicines

         # Handle pagination
        per_page = int(self.request.GET.get('per_page', 10))  # Get the number of items per page from the GET parameters, default to 10
        paginator = Paginator(context['medicines'], per_page)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context['page_obj'] = page_obj
        context['per_page'] = per_page

        return context

class UserListView(LoginRequiredMixin, AdminRequiredMixin, ListView):
    model = User
    template_name = 'user_list.html'  # Replace with your template name
    context_object_name = 'users'
    
def contact_view(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']
        
        # Format the email content for admin with improved HTML
        email_content = f"""
        <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.5;">
                <p><strong>Name:</strong> {name}</p>
                <p><strong>Email:</strong> {email}</p>
                <p><strong>Message:</strong></p>
                <p style="background-color: #f0f8ff; padding: 5px; margin: 0;">{message}</p>
            </body>
        </html>
        """
        
        # Send email to admin
        send_mail(
            f'Contact Us Form Submission from {name}',
            email_content,
            settings.DEFAULT_FROM_EMAIL,
            ['firstaidkitmgmt@gmail.com'],
            fail_silently=False,
            html_message=email_content
        )

        # Format the email content for user confirmation with improved HTML
        confirmation_email_content = f"""
        <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.5;">
                <p>Hi {name},</p>
                <p>Thank you for contacting us! Your message has been received, and we will get back to you shortly.</p>
                <p><strong>Here is a copy of your message:</strong></p>
                <p style="background-color: #f0f8ff; padding: 5px; margin: 0;">{message}</p>
                <p>Best regards,</p>
                <p>Admin Team</p>
            </body>
        </html>
        """

        # Send confirmation email to the user
        send_mail(
            'Confirmation of Your Contact Form Submission',
            confirmation_email_content,
            settings.DEFAULT_FROM_EMAIL,
            [email],
            fail_silently=False,
            html_message=confirmation_email_content
        )
        
        messages.success(request, 'Your message has been sent successfully!')
        return redirect('login')  # Redirect to the login page

    return render(request, 'contact.html')


def custom_404(request, exception):
    return render(request, '404.html', status=404)


def test_404_view(request):
    raise Http404("This is a test 404 error.")

base/templates/base/contact.html
{% extends 'base/main.html' %}
{% block content %}

<div class="container mt-4">
    <div class="mb-4">
        <h1>Contact Us</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" id="name" name="name" class="form-control mb-3" required>
                </div>

                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" class="form-control mb-3" required>
                </div>

                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea id="message" name="message" class="form-control mb-3" rows="5" required></textarea>
                </div>
                
                <button class="btn btn-dark btn-block" type="submit">Send</button>
            </form>
            <p class="mt-3">Need assistance? <a href="{% url 'login' %}">Login</a></p>
        </div>
    </div>
</div>

{% endblock content %}

base/templates/base/login.html
{% extends 'base/main.html' %}
{% block content %}

<div class="container mt-4">
    <div class="mb-4">
        <h1>Login</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="form-group">
                <form method="POST">
                    {% csrf_token %}
                    
                    <label for="username">User Name</label>
                    <input type="text" id="username" name="username" class="form-control mb-3" placeholder="Email or Phone" required>
                    
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" class="form-control mb-3" placeholder="Password" required>
                    
                    <button class="btn btn-dark btn-block" type="submit">Login</button>
                </form>
            </div>
            <p class="mt-3">Don't have an account? <a href="{% url 'register' %}">Register</a></p>
            <p class="mt-3">Need assistance? <a href="{% url 'contact' %}">Contact Us</a></p>
        </div>
    </div>
</div>

{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>First Aid Kit Management</title>
</head>
<body>
    <div class="container">
        {% block content %} {% endblock content %}
    </div>
</body>
</html>

base/templates/base/medicine_confirm_delete.html
{% extends 'base/main.html' %}
{% block content %}

<div class="container mt-4">
    <a href="{% url 'medicines' %}" class="btn btn-primary">Go Back</a>
</div>

<div class="container mt-4">
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete this medicine record? <b>"{{medicine}}"</b> </p>
        <input class="btn btn-danger" type="submit" value="Delete" />
    </form>
</div>



{% endblock content %}

base/templates/base/medicine_detail.html
{% extends 'base/main.html' %}
{% block content %}

<div class="container mt-4">
    <h2 class="mb-3">Medicine Description</h2>
    <div class="card">
        <div class="card-body">
            <p class="card-text">This medicine is used for <strong>{{ medicine.description }}</strong>.</p>
        </div>
    </div>
</div>

{% endblock %}

base/templates/base/medicine_form.html
{% extends 'base/main.html' %}
{% block content %}

<div class="container mt-4">
    <a href="{% url 'medicines' %}" class="btn btn-primary">Go Back</a>
</div>

<div class="container mt-4">
    <h2 class="mb-4">Submit Form</h2>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% if request.user.is_staff %}
        <div class="form-group">
            {{ form.user.label_tag }}
            {{ form.user }}
            {{ form.user.errors }}
        </div>
        {% endif %}
        <div class="form-group">
            {{ form.medicine_name.label_tag }}
            {{ form.medicine_name }}
            {{ form.medicine_name.errors }}
        </div>
        <div class="form-group">
            {{ form.description.label_tag }}
            {{ form.description }}
            {{ form.description.errors }}
        </div>
        <div class="form-group">
            {{ form.quantity.label_tag }}
            {{ form.quantity }}
            {{ form.quantity.errors }}
        </div>
        <div class="form-group">
            {{ form.expiry_date.label_tag }}
            {{ form.expiry_date }}
            {{ form.expiry_date.errors }}
        </div>
        
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>

{% endblock %}

base/templates/base/medicine_list.html
{% extends 'base/main.html' %}

{% block content %}

<div class="container mt-4">
    <div class="row">
        <div class="col-12">
            {% if request.user.is_staff %}
                <h1>Hello <a href="/admin">{{ request.user|title }}</a></h1>
            {% else %}
                <h1>Hello {{ request.user|title }}</h1>
            {% endif %}
        </div>
    </div>
    
    <div class="row">
        <div class="col-12">
            {% if request.user.is_authenticated %}
            <form action="{% url 'logout' %}" method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger">Logout</button>
            </form>
            {% else %}
            <a href="{% url 'login' %}" class="btn btn-outline-primary">Login</a>
            {% endif %}
        </div>
    </div>
</div>

{% if expiring_medicines and not request.user.is_staff %}
<div class="alert alert-warning mt-4">
    <strong>Alert!</strong> The following medicines will expire within the next month:
    <ul>
        {% for medicine in expiring_medicines %}
        <li>{{ medicine.medicine_name }} (Expiry Date: {{ medicine.expiry_date }})</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<div id="search-add-wrapper" class="mt-4 col-12 col-lg-6 mx-auto">
    <form method="GET" class="form-inline d-flex flex-nowrap">
        <input type="text" name="search-area" class="form-control mr-2 flex-grow-1" placeholder="Search your medicine" value="{{ search_input }}">
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
</div>

<div class="container mt-4">
    <h2 class="mb-3">Medicines List</h2>
    <div class="mb-3 d-flex justify-content-between align-items-center">
        <a href="{% url 'medicine-create' %}" class="btn btn-success">Add Medicine</a>
        {% if request.user.is_staff %}
            <a href="{% url 'user-list' %}" class="btn btn-info">View All Users</a>
        {% endif %}
    </div>

    <div class="mb-3">
        <form method="GET" class="form-inline d-flex flex-wrap align-items-center">
            <div class="form-group mb-1 mb-sm-0 d-flex align-items-center">
                <label for="per_page" class="sr-only">Show</label>
                <span class="mr-2">Show</span>
                <select id="per_page" name="per_page" class="form-control" onchange="this.form.submit()">
                    <option value="10" {% if per_page == 10 %}selected{% endif %}>10</option>
                    <option value="20" {% if per_page == 20 %}selected{% endif %}>20</option>
                    <option value="50" {% if per_page == 50 %}selected{% endif %}>50</option>
                </select>
            </div>
            <div class="form-group mb-1 mb-sm-0 d-flex align-items-center">
                <label for="entries" class="sr-only">entries</label>
                <span class="ml-2">entries</span>
            </div>
            <input type="hidden" name="search-area" value="{{ search_input }}">
            <!-- Keep the page number in the URL to maintain pagination state -->
            <input type="hidden" name="page" value="{{ page_obj.number }}">
        </form>
    </div>
    
    

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Sr.No</th>
                    <th scope="col">Medicine</th>
                    <th scope="col">Description</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Expiry Date</th>
                    {% if request.user.is_staff %}
                    <th scope="col">User</th>
                    {% endif %}
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for medicine in page_obj %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ medicine.medicine_name }}</td>
                    <td><a href="{% url 'medicine' medicine.id %}">{{ medicine.description }}</a></td>
                    <td>{{ medicine.quantity }}</td>
                    <td class="{% if medicine in expiring_medicines %}text-danger{% endif %}">{{ medicine.expiry_date }}</td>
                    {% if request.user.is_staff %}
                    <td>
                        <a href="{% url 'user-medicines' medicine.user.id %}">{{ medicine.user.username }}</a>
                    </td>  
                    {% endif %}
                    <td class="d-flex">
                        <a href="{% url 'medicine-update' medicine.id %}" class="btn btn-sm btn-primary">Edit</a>
                        <a href="{% url 'medicine-delete' medicine.id %}" class="btn btn-sm btn-danger ml-1">Delete</a>
                    </td>
                </tr>
                {% empty %}
                {% if request.user.is_staff %}
                    <tr>
                        <td colspan="7" class="text-center">No medicines in List</td>
                    </tr>
                {% else %}
                <tr>
                    <td colspan="6" class="text-center">No medicines in List</td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>

    <br>

    <!-- Pagination -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1&per_page={{ per_page }}&search-area={{ search_input }}" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}&per_page={{ per_page }}&search-area={{ search_input }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active">
                        <span class="page-link">{{ num }}<span class="sr-only">(current)</span></span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}&per_page={{ per_page }}&search-area={{ search_input }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}&per_page={{ per_page }}&search-area={{ search_input }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&per_page={{ per_page }}&search-area={{ search_input }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

{% endblock content %}

base/templates/base/register.html
{% extends 'base/main.html' %}
{% block content %}

<div class="container mt-4">
    <div class="header-bar mb-4">
        <h1>Register</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
               {{form}}
                <button class="btn btn-primary mt-3" type="submit">Register</button>
            </form>
            <p class="mt-3">Already have an account? <a href="{% url 'login' %}">Login</a></p>
            <p class="mt-3">Need assistance? <a href="{% url 'contact' %}">Contact Us</a></p>
        </div>
    </div>
</div>

{% endblock content %}

base/templates/base/user_list.html
{% extends 'base/main.html' %}

{% block content %}

<div class="container mt-4">
    <h2>All Users</h2>
    <div class="mb-3">
        <a href="{% url 'medicines' %}" class="btn btn-secondary">Back to Home</a>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Username</th>
                <!-- <th scope="col">Email</th> -->
                <th scope="col" class="text-center">Medicines Count</th>
                <!-- <th scope="col">Medicines</th> -->
                <!-- Add more fields as needed -->
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td><a href="{% url 'user-medicines' user.id %}">{{ user.username }}</a></td>
                <!-- <td>{{ user.email }}</td> -->
                <td class="text-center">
                    {{ user.medicine_set.count }}
                </td>
                <!-- <td>
                    {% for medicine in user.medicine_set.all %}
                        {{ medicine.medicine_name }} (Expiry Date: {{ medicine.expiry_date }})<br>
                    {% empty %}
                        No medicines
                    {% endfor %}
                </td> -->
                
                <!-- Add more columns for other user details or actions -->
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">No users found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}